### ISSUE TITLE
Add support for Cline, Roo Cline, zed etc.

### ISSUE THREAD

**Issue by ichoosetoaccept** [smithery-ai/typescript-sdk#12]
See the example clients matrix here: https://modelcontextprotocol.io/clients

Since Smithery currently is a very nice wrapper for editing Claude's settings claude_desktop_config.json file, you could add support for more clients.

Currently Cline and Roo Cline would be easiest as they use the exact same JSON structure as Claude as well as the same file.

It lives here on macOS: "/Users/username/Library/Application Support/code/globalStorage/saoudrizwan.claude-dev/settings/cline_mcp_settings.json"

On running a smithery NPX call, you could check if this path exists and ask the user if, in addition to Claude Desktop, they want to add the server to Cline/Roo Cline as well.

Unlike Claude desktop, these VS Code extensions do not require client restarts for new MCP servers to show up. They seem to watch the file for changes continuously (something Claude Desktop may want to adopt as well).

**Comment by calclavia** [comment]
@ichoosetoaccept Great idea - would you be open to creating a PR for the clients you're familiar with? I've never used Cline before.

This is the open source repo for the CLI: https://github.com/smithery-ai/cli

**Comment by calclavia** [comment]
Moved issue to: https://github.com/smithery-ai/cli/issues/1
