### ISSUE TITLE
Mozilla Readability Parser MCP Server

### ISSUE THREAD

**Issue by emzimmer** [smithery-ai/typescript-sdk#15]
Link to MCP repository: https://github.com/emzimmer/server-moz-readability

Extracts and transforms webpage content into clean, LLM-optimized Markdown. Returns article title, main content, excerpt, byline and site name. Uses Mozilla's Readability algorithm to remove ads, navigation, footers and non-essential elements while preserving the core content structure.

**Comment by calclavia** [comment]
Done: https://smithery.ai/server/server-moz-readability
