### ISSUE TITLE
Installation Prompts - How to Configure?

### ISSUE THREAD

**Issue by evalstate** [smithery-ai/typescript-sdk#6]
![image](https://github.com/user-attachments/assets/36d6b83b-e6ae-415b-9b60-ed308885095b)

How can we set this up so that it accepts empty/defaults and doesn't duplicate the command line option and environment vars?

**Comment by calclavia** [comment]
@arjunkmrm Could you take a look at this?

It'll be a good idea for us to assign defaults to the MCP configs so installation is faster (you can just spam ENTER to get all defaults)

**Comment by evalstate** [comment]
Hey - so for this example the Hugging Face token can be supplied by either an ENV or command line option, with the latter taking precedence. It can also be empty. So ideal behaviour would be for it to just prompt for one or the other - and to indicate to the user that there is a default (blank) or <PRESS ENTER FOR DEFAULT> or something to make it easy for casual users to install.

**Comment by evalstate** [comment]
also in this case, CLAUDE_DESKTOP_MODE defaults to <true> if not specified - that's intended.

**Comment by calclavia** [comment]
Appreciate the feedback @evalstate - we'll look into adding this improvement!

**Comment by arjunkmrm** [comment]
the latest changes have resolved this issue by creating a 'set' of vars for prompting, and prioritises env vars to remove dupes in command line args.
